### PR TITLE
init Poetry and other setup req

### PR DESCRIPTION
**Pull request by SalMireles**
As a developer I want to efficiently boot up my virtual environment with all the required dependencies
As a developer I don't want to have lingering sub dependencies when updating and or removing  main dependencies (see here for more wins: https://nanthony007.medium.com/stop-using-pip-use-poetry-instead-db7164f4fc72)

This PR add a few projects setup tools:

1. Adds poetry to manage dependencies 
2. Updates readme with first time setup info
3. Adds Makefile to start up virtual environment with a one liner

### CODE REVIEW

**Review by Scott-Larsen — APPROVED** [review]
Looks good to me.

**Review by misaacs — APPROVED** [review]

**Comment by SalMireles** [comment]
> Isn't it better to pin one or two really things important things(eg a python = "~3.8.10" ie allowing bug fix updates in the python 3.8 while holding it off 3.9/3.10 ) and allowing more flexibility for poetry to update with things like black & flake8 where it doesn't matter that much (I actually prefer the previous black & flake8 specs; could even go more flexible "^22" and "^4" ) but I'll defer to your previous experiences with these.

Good point. There will be bug fixes and security upgrades and packages will need to be bumped. IMO I think all packages should be pinned to avoid and breaking our code and updates should be intentional. That does remind me that our dev packages should be listed under dev. I’ll update that to move towards poetries planned grouping structure https://python-poetry.org/docs/master/managing-dependencies/

**Review by misaacs — APPROVED** [review]

**Comment by misaacs** [comment]
Good point Sal about black, flake8 & pytest should all be in dev-dependencies section of the toml; I think those libraries are not added to the release builds

**Comment by lildonpancho** [comment]
Note that minor fixes and patches are backward compatible and should not break anything. Only major upgrades tend to have breaking changes. That being said, I usually pin to the minor version to allow for bug fixes.

**Pull request merged**
